### ISSUE TITLE
Difficult to edit large local storage value

### ISSUE THREAD

**Issue by kuhiga** [imlinhanchao/crx_storage_editor#1]
Hi, first of all, thanks for making this extension. Currently when editing large json objects, the text edit field is hard to use since the text input box is small. Is it possible to make changes to display a modal when editing values, or expand the text input area? 

<img width="677" alt="Screenshot 2024-01-29 at 4 17 47 PM" src="https://github.com/imlinhanchao/crx_storage_editor/assets/34705627/a1befd8d-1e4e-4e94-9216-cfcbda4be685">

**Comment by imlinhanchao** [comment]
OK~ I will update this week.

**Comment by imlinhanchao** [comment]
It's support now. You can download 1.0.2 from [release](https://github.com/imlinhanchao/crx_storage_editor/releases/tag/1.0.2). Or waiting for Store Publish (maybe need few days).

**Comment by kuhiga** [comment]
I just tested the update from the store. This was exactly what I needed, thank you for the quick turn around! @imlinhanchao
