### ISSUE TITLE
Chrome 130版本不兼容问题

### ISSUE THREAD

**Issue by DexYang** [imlinhanchao/crx_storage_editor#2]
作者您好，

前些天chrome更新后，这个扩展出现错误：

content-script-loader.index.ts.c957594d.5c55b11c.js:7 

Refused to load the script 'chrome-extension://32d8d1c3-700b-4226-960a-7457cfff52c6/assets/index.ts.c957594d.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

 看起来是chrome安全策略有更新影响了这个扩展，麻烦作者看一下

**Comment by imlinhanchao** [comment]
看起来是 Chrome  的 bug：https://issues.chromium.org/issues/363027634?pli=1

我想办法兼容吧。

**Comment by imlinhanchao** [comment]
已修正，等待浏览器推送更新吧。1.0.3

**Comment by imlinhanchao** [comment]
Chrome 版本已发布，确认问题已解。Close #2
